"""Expand columns

Revision ID: 612a06471185
Revises: 7f3889f713c4
Create Date: 2026-02-26 06:01:12.501346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '612a06471185'
down_revision = '7f3889f713c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exhibits', schema=None) as batch_op:
        batch_op.alter_column('exhibit_name',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.alter_column('primary_image_small',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('region',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=250),
               existing_nullable=True)
        batch_op.alter_column('culture',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=250),
               existing_nullable=True)
        batch_op.alter_column('object_date',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=250),
               existing_nullable=True)
        batch_op.alter_column('artist_name',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=500),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=300),
               existing_nullable=False)
        batch_op.alter_column('profile_image',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=290),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('profile_image',
               existing_type=sa.String(length=290),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)

    with op.batch_alter_table('exhibits', schema=None) as batch_op:
        batch_op.alter_column('artist_name',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)
        batch_op.alter_column('object_date',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('culture',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('region',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('primary_image_small',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)
        batch_op.alter_column('exhibit_name',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)

    # ### end Alembic commands ###
